public class LeftShift{
	public static void main(String[] args){
	String s1 = "0xFFF";
	long l1 = 0xFFF;
	System.out.println("l1: " + l1);
	System.out.println("s1 hex: " + Long.toHexString(l1));
	System.out.println(Long.toBinaryString(l1));
	l1 <<= 1;
	System.out.println("l1: " + l1);
	System.out.println("s1 hex: " + Long.toHexString(l1));
	System.out.println(Long.toBinaryString(l1));
	l1 >>>= 1;
	System.out.println("l1: " + l1);
	System.out.println("s1 hex: " + Long.toHexString(l1));
	System.out.println(Long.toBinaryString(l1));
	l1 >>>= 1;
	System.out.println("l1: " + l1);
	System.out.println("s1 hex: " + Long.toHexString(l1));
	System.out.println(Long.toBinaryString(l1));
	l1 >>>= 1;
	System.out.println("l1: " + l1);
	System.out.println("s1 hex: " + Long.toHexString(l1));
	System.out.println(Long.toBinaryString(l1));
	l1 >>>= 1;
	System.out.println("l1: " + l1);
	System.out.println("s1 hex: " + Long.toHexString(l1));
	System.out.println(Long.toBinaryString(l1));
	l1 >>>= 1;
	System.out.println("l1: " + l1);
	System.out.println("s1 hex: " + Long.toHexString(l1));
	System.out.println(Long.toBinaryString(l1));
	l1 >>>= 1;
	System.out.println("l1: " + l1);
	System.out.println("s1 hex: " + Long.toHexString(l1));
	System.out.println(Long.toBinaryString(l1));
	l1 >>>= 1;
	System.out.println("l1: " + l1);
	System.out.println("s1 hex: " + Long.toHexString(l1));
	System.out.println(Long.toBinaryString(l1));
	l1 >>>= 1;
	System.out.println("l1: " + l1);
	System.out.println("s1 hex: " + Long.toHexString(l1));
	System.out.println(Long.toBinaryString(l1));
	l1 >>>= 1;
	System.out.println("l1: " + l1);
	System.out.println("s1 hex: " + Long.toHexString(l1));
	System.out.println(Long.toBinaryString(l1));
	l1 >>>= 1;
	System.out.println("l1: " + l1);
	System.out.println("s1 hex: " + Long.toHexString(l1));
	System.out.println(Long.toBinaryString(l1));
	l1 >>>= 1;
	System.out.println("l1: " + l1);
	System.out.println("s1 hex: " + Long.toHexString(l1));
	System.out.println(Long.toBinaryString(l1));
	l1 >>>= 1;
	System.out.println("l1: " + l1);
	System.out.println("s1 hex: " + Long.toHexString(l1));
	System.out.println(Long.toBinaryString(l1));
	l1 >>>= 1;
	System.out.println("l1: " + l1);
	System.out.println("s1 hex: " + Long.toHexString(l1));
	System.out.println(Long.toBinaryString(l1));
	l1 >>>= 1;
	System.out.println("l1: " + l1);
	System.out.println("s1 hex: " + Long.toHexString(l1));
	System.out.println(Long.toBinaryString(l1));
	l1 >>>= 1;
	System.out.println("l1: " + l1);
	System.out.println("s1 hex: " + Long.toHexString(l1));
	System.out.println(Long.toBinaryString(l1));
	l1 >>>= 1;
	System.out.println("l1: " + l1);
	System.out.println("s1 hex: " + Long.toHexString(l1));
	System.out.println(Long.toBinaryString(l1));
	l1 >>>= 1;
	}
}
